Add option to sign tokens with x5c chains
vapor/jwt-kit pull request #126
Opened 2023-11-23 22:08 UTC by ptoffy

This adds a new `x5c` parameter to the sign method, which accepts an array of pem encoded certificates which form an x5c chain. This chain gets added to the JWT's header with the `x5c` field. For the token to be valid, it must be signed with the leaf certificate's private key

2023-11-23 22:15 UTC, gwynne approved these changes

2023-11-23 22:48 UTC, 0xTim requested changes
Looking good, a couple of questions and more tests needed

2023-11-23 22:48 UTC, 0xTim commented on Sources/JWTKit/JWTSerializer.swift
> +            try await verifier.verifyChain(certificates: x5c)
We may want to add a flag to disable verification, for testing etc. But I'm not sure if this is explicitly disallowed

2023-11-23 22:48 UTC, 0xTim commented on Sources/JWTKit/X5C/X5CVerifier.swift
> +    package func verifyChain(certificates: [String]) async throws {
Does this need to be package protected instead of internal?

2023-11-23 22:48 UTC, 0xTim commented on Tests/JWTKitTests/X5CTests.swift
> +    func testSigningWithX5CChain() async throws {
We should test a chain with a cert that isn't verified by the node above to make sure it throws an error

2023-11-24 11:40 UTC, 0xTim approved these changes

2023-11-24 14:53 UTC, merged