Update CI
vapor/jwt-kit pull request #137
Opened 2024-02-19 19:12 UTC by ptoffy

- Show warnings as errors
- Add benchmark CI using https://github.com/ordo-one/package-benchmark

2024-02-20 11:00 UTC, 0xTim approved these changes

2024-02-22 11:40 UTC, 0xTim commented
@ptoffy this will need rebasing

2024-02-23 10:50 UTC, gwynne requested changes

2024-02-23 10:50 UTC, gwynne commented on .github/workflows/benchmark.yml
> +          exit ${{ env.exitStatus }}
```suggestion
name: Benchmark PR vs main
on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]
  
jobs:
  benchmark-delta-linux:
    runs-on: ubuntu-latest
    container: swift:jammy
    steps:
      - uses: actions/checkout@v4
      - name: jemalloc dependency
        run: sudo apt-get update && sudo apt-get install -y libjemalloc-dev
      - name: Run benchmarks for PR branch
        if: ${{ hashFiles('Benchmarks/**') != '' }}
        run: |
          swift package --allow-writing-to-directory .benchmarkBaselines/ benchmark baseline update pull_request
          git checkout main
          swift package --allow-writing-to-directory .benchmarkBaselines/ benchmark baseline update main
          date >>"${GITHUB_STEP_SUMMARY}"
          swift package benchmark baseline check main pull_request --format markdown >>"${GITHUB_STEP_SUMMARY}"
        uses: thollander/actions-comment-pull-request@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          message: ${{ format('[PR benchmark comparison Linux|main]({0}/{1}/actions/runs/{2})', github.server_url, github.repository, github.run_id) }}
          comment_tag: 'PR benchmark comparison Linux'
```

2024-02-23 10:50 UTC, gwynne commented on .github/workflows/test.yml
> +        run: swift test --package-path jwt --sanitize=thread -Xswiftc -warnings-as-errors
This is a good way to make sure CI never ever passes, given the way warnings tend to show up without warning (no pun intended) thanks to changes in dependencies.

2024-02-24 22:24 UTC, closed without merging

2024-02-24 22:29 UTC, ptoffy commented
Closed in favour of #141