Add benchmark CI
vapor/jwt-kit pull request #141
Opened 2024-02-24 22:28 UTC by ptoffy

2024-02-24 22:41 UTC, gwynne approved these changes
Assuming it actually works as written (I couldn't exactly test it, after all!), approved 😛

2024-02-24 22:43 UTC, gwynne requested changes
For example, like that...

2024-02-24 22:43 UTC, gwynne commented on .github/workflows/benchmark.yml
> +        uses: thollander/actions-comment-pull-request@v2
```suggestion
      - uses: thollander/actions-comment-pull-request@v2
```

2024-02-24 22:49 UTC, gwynne commented on .github/workflows/benchmark.yml
> +        run: sudo apt-get update && sudo apt-get install -y libjemalloc-dev
```suggestion
        run: apt-get update && apt-get install -y libjemalloc-dev
```

2024-03-20 17:28 UTC, 0xTim approved these changes
LGTM - will let @gwynne approve as well

2024-03-26 11:31 UTC, gwynne approved these changes

2024-03-26 11:31 UTC, gwynne commented on Benchmarks/Package.swift
> +        .package(path: "../"),
I realize this is the way this tooling work, but it makes me shudder just the same 🤦‍♀️

2024-03-26 11:43 UTC, merged