add curve and parameters properties to ECDSAKey protocol
vapor/jwt-kit pull request #143
Opened 2024-03-14 17:03 UTC by JaapWijnen

This adds curve and parameter properties to the ECDSAKey protocol and also makes them public (non settable) on the ECDSA.PublicKey<Curve> and ECDSA.PrivateKey<Curve> types.

2024-03-14 17:18 UTC, JaapWijnen commented
Not sure what's going on with CI here. Any ideas? @ptoffy or @gwynne ?

2024-03-14 21:45 UTC, ptoffy commented
@JaapWijnen yeah looks like this isn't you, the same error is happening all over Vapor repos. There's probably something wrong with GH's CI or similar

2024-03-14 21:50 UTC, ptoffy requested changes
While we're making these public, could you please move tests such as https://github.com/vapor/jwt-kit/blob/main/Tests/JWTKitTests/InternalTests.swift#L7 to the `ECDSATests` file so we can minify internal tests as much as possible? Thanks!

2024-03-15 21:49 UTC, ptoffy approved these changes

2024-03-15 21:49 UTC, merged