Add FirebaseAuth identity token
vapor/jwt-kit pull request #207
Opened 2024-10-17 07:18 UTC by petrpavlik

- Add support for Firebase Auth by introducing `FirebaseAuthIdentityToken`. 
- Fix some unit tests not being run. Probably a regression cause by migration to the new testing framework.

Adding support for Firebase Authentication was okayed by @ptoffy, see here https://github.com/vapor/jwt/issues/159.

I'll also follow up with a PR for https://github.com/vapor/jwt once this is merged in.

2024-10-17 07:41 UTC, ptoffy requested changes
Thanks for this! Just missing some formatting. Feel free to run `swift format --recursive --in-place .` with https://github.com/vapor/contributing/blob/main/.swift-format in the project's directory. While you're at it could you add some names to the `@Test`s which were missing? Something similar to the other test suites should be fine

2024-10-18 08:01 UTC, petrpavlik commented
@ptoffy done, please take another look.

Not sure though why the windows CI pass failed on some CCryptoBoringSSL (linker?) errors?

2024-10-18 11:22 UTC, ptoffy commented
Yeah looks like this should fix it https://github.com/apple/swift-crypto/commit/4518e5e680ea71b60d5c4644939bdeebbb0301e1 but there hasn't been a release yet

2024-10-18 11:27 UTC, ptoffy requested changes
Just a few whitespace nits to be in par with the rest of the repo. I would have thought swift-format would catch these but maybe we need to be stricter 🤷

2024-10-18 11:27 UTC, ptoffy commented on Sources/JWTKit/Vendor/FirebaseAuthIdentityToken.swift
> +
Nit: could you remove this whitespace along with the others to conform to the rest of the repo?

2024-10-18 11:27 UTC, ptoffy commented on Sources/JWTKit/Vendor/FirebaseAuthIdentityToken.swift
> +
Nit: whitespace

2024-10-18 11:27 UTC, ptoffy commented on Sources/JWTKit/Vendor/FirebaseAuthIdentityToken.swift
> +
Nit: whitespace

2024-10-18 11:27 UTC, ptoffy commented on Tests/JWTKitTests/VendorTokenTests.swift
> +
Nit: whitespace

2024-10-18 11:27 UTC, ptoffy commented on Tests/JWTKitTests/VendorTokenTests.swift
> +
Nit: whitespace

2024-10-18 11:54 UTC, petrpavlik commented
Thanks, I'll fix those. Yeah, I just ran swift-format before pushing the changes, relying on that I'd fix everything for me.

2024-10-18 16:28 UTC, ptoffy approved these changes
Thanks!

2024-10-18 16:28 UTC, merged