Move away from BoringSSL
vapor/jwt-kit pull request #99
Opened 2023-10-09 14:59 UTC by ptoffy

This aims to remove most if not all usages of BoringSSL and replace it with [swift-crypto](https://github.com/apple/swift-crypto/) and [swift-certificates](https://github.com/apple/swift-certificates)

2023-10-24 19:03 UTC, 0xTim reviewed
The code changes in the actual business logic that go from hundreds of lines of horrible unsafe code to a few nice lines of Swift are amazing

Initial comments

2023-10-24 19:03 UTC, 0xTim commented on Tests/JWTKitTests/X5CTests.swift
> +func XCTAssertNoThrowAsync<T>(
These should be in a separate file

2023-10-24 19:03 UTC, 0xTim commented on Tests/JWTKitTests/JWTKitTests.swift
> +    import FoundationNetworking
Do we need this

2023-10-24 19:03 UTC, 0xTim commented on Package.swift
> +        .package(url: "https://github.com/apple/swift-crypto.git", "2.6.0" ..< "4.0.0"),
Let's just do 3.X.X for now

2023-10-24 19:03 UTC, 0xTim commented on Package.swift
> +    cxxLanguageStandard: .cxx11
I don't think we need this anymore

2023-10-27 20:05 UTC, gwynne requested changes
Bunches of nits all hither and thither

2023-10-27 20:05 UTC, gwynne commented on Sources/JWTKit/Utilities/Base64URL.swift
>          }
```swift
        for idx in self.indices {
            switch self[idx] {
            case 0x2d/* - */: self[idx] = 0x2b/* + */
            case 0x5f/* _ */: self[idx] = 0x2f/* / */
            default: break
            }
        }
```
Not only more readable but HUGELY more efficient...

2023-10-27 20:05 UTC, gwynne commented on Sources/JWTKit/Utilities/Base64URL.swift
>          }
```swift
        for idx in self.indices {
            switch self[idx] {
            case 0x2b/* + */: self[idx] = 0x2d/* - */
            case 0x2f/* / */: self[idx] = 0x5f/* _ */
            default: break
            }
        }
```
Not only more readable but HUGELY more efficient...

2023-10-28 13:08 UTC, 0xTim approved these changes
There's probably a bit more work we can do on docs, like ensuring all types are linked, everything is public, a basic usage index page etc etc but that can all be done later.

BoringSSL removed! 🥳

2023-10-28 13:23 UTC, merged